name: Test Builds

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

concurrency:
  group: test-builds-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Android build script
        run: bash scripts/build.android.sh  --debug

  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Web build script
        run: bash scripts/build.web.sh --debug

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run iOS build script
        run: bash scripts/build.ios.sh  --debug
